# version: '3.9'

# services:

#   # Redis
#   redis:
#     restart: always
#     image: redis:alpine
#     container_name: redis_db

#   # Database PostgreSQL
#   db:
#     image: postgres
#     restart: always
#     # volumes:
#     #   - ./db_data:/var/lib/postgresql/data
#     env_file:
#       - ./.env.dev
#     container_name: postgres_db

#   # Django Backend Application API
#   backend:
#     restart: always
#     build:
#       context: ./backend/
#       dockerfile: Dockerfile
#     volumes:
#       - .:/django
#       - ./data/web:/var/www/web
#     ports:
#       - 8000:8000
#     container_name: backend_django
#     command: gunicorn core.wsgi --bind 0.0.0.0:8000 --reload
#     env_file:
#       - ./.env.dev
#     depends_on:
#       - db

#   # Celery
#   celery:
#     restart: always
#     build:
#       context: ./backend/
#     command: celery -A core worker -l DEBUG
#     container_name: celery
#     env_file:
#       - ./.env.dev
#     depends_on:
#       - db
#       - redis
#       - backend

#   # React Frontend Application CLI
#   frontend:
#     restart: always
#     command: npm start
#     build:
#       context: ./frontend/
#       target: production
#       dockerfile: Dockerfile
#     container_name: frontend_react
#     ports:
#       - 3000:3000
#     depends_on:
#       - backend

#   # Web Server
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     build:
#       context: ./nginx/
#       dockerfile: Dockerfile
#     ports:
#       - 80:8080
#     depends_on:
#       - backend
#       - frontend