# Generated by Django 4.2.4 on 2023-08-20 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('album', models.CharField(blank=True, null=True)),
                ('artist', models.CharField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('name', models.CharField()),
                ('channelId', models.CharField(max_length=200)),
                ('channelUrl', models.URLField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('name', models.CharField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('name', models.CharField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deleted', models.UUIDField(blank=True, default=None, null=True)),
                ('extractor', models.IntegerField(blank=True, choices=[(1, 'file'), (2, 'youtube'), (3, 'soundcloud'), (4, 'spotify'), (5, 'vimeo')], default=1, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Queued'), (2, 'Downloading'), (3, 'Finished'), (4, 'Error')], default=1, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(unique=True)),
                ('title', models.TextField(blank=True)),
                ('duration', models.DurationField(default=0)),
                ('release_date', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(blank=True, editable=False, null=True, upload_to='')),
                ('thumbnail_file', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('url_thumbnail', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('age_limit', models.IntegerField(default=0)),
                ('audio_bitrate', models.IntegerField(blank=True, null=True)),
                ('audio_protocol', models.CharField(blank=True, null=True)),
                ('audio_extension', models.CharField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_song.album')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_song.author')),
                ('categories', models.ManyToManyField(blank=True, to='apis_song.categories')),
                ('tags', models.ManyToManyField(blank=True, to='apis_song.tags')),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
